---
sudo: false
language: ruby
cache: bundler
matrix:
  include:
  - rvm: jruby-9.1.13.0
    env: LOGSTASH_BRANCH=master
  - rvm: jruby-9.1.13.0
    env: LOGSTASH_BRANCH=7.x
  - rvm: jruby-9.1.13.0
    env: LOGSTASH_BRANCH=6.7
  fast_finish: true
install: true
script: ci/build.sh
jdk: oraclejdk8
